export const AUTHENTICATE = 'AUTHENTICATE'
export const GET_PROFILE = 'GET_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD'
export const CONFIRM_RESET_PASSWORD = 'CONFIRM_RESET_PASSWORD'
export const LOGOUT = 'LOGOUT'

export const GET_NOTES = 'GET_NOTES'
export const GET_PERFUMES = 'GET_PERFUMES'
export const GET_BRANDS = 'GET_BRANDS'

export const SEARCH_ALL = 'SEARCH_ALL'
export const SEARCH_NOTES = 'SEARCH_NOTES'
export const SEARCH_PERFUMES = 'SEARCH_PERFUMES'
export const SEARCH_BRANDS = 'SEARCH_BRANDS'

export const DEMO_REQUEST = 'DEMO_REQUEST'
export const NEWSLETTER_SIGNUP = 'NEWSLETTER_SIGNUP'
export const CONTACT_REQUEST = 'CONTACT_REQUEST'

export const GET_CREATIONS = 'GET_CREATIONS'

export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST'
export const ADD_CLIENTS = 'ADD_CLIENTS'
export const ADD_CLIENTS_REQUEST = 'ADD_CLIENTS_REQUEST'
export const CREATE_CLIENT_MODAL = 'CREATE_CLIENT_MODAL'
export const INVITE_CLIENT = 'INVITE_CLIENT'
export const GET_EVENTS = "GET_EVENTS"